### ISSUE TITLE
一些编辑错误

### ISSUE THREAD

**Issue by SheilaLundin** [hantmac/Mastering_Go_ZH_CN#102]
13.6.1 简洁的并发TCP服务器
`encode := gob.NewEncoder(saveTo)` 应为 `encoder := gob.NewEncoder(saveTo)`
`n := myElement(tokens[2], tokens[3], tokens[4])` 应为 `n := myElement{tokens[2], tokens[3], tokens[4]}`

**Comment by hantmac** [comment]
感谢校正。
本书翻译接近尾声，期待你参与整本书的校正🍺。
