### ISSUE TITLE
07.1 类型方法 一节中代码引用的格式错误

### ISSUE THREAD

**Issue by iondex** [hantmac/Mastering_Go_ZH_CN#128]
如图所示：
![image](https://user-images.githubusercontent.com/4617752/58890875-0db14200-871e-11e9-8e3a-82ecabc3e4a8.png)

Gitbook章节链接：https://wskdsgcf.gitbook.io/mastering-go-zh-cn/7-fan-she-he-jie-kou/07.1

编辑：用Github自带的Markdown阅读器可以正确渲染，但在Gitbook上就会有渲染问题

![image](https://user-images.githubusercontent.com/4617752/58891097-7f898b80-871e-11e9-9ae4-f292d55bc0f8.png)

**Comment by hantmac** [comment]
@wskdsgcf 昆神帮忙看下这个问题
