### ISSUE TITLE
图片显示不出来

### ISSUE THREAD

**Issue by dreamer2q** [hantmac/Mastering_Go_ZH_CN#142]
![image](https://user-images.githubusercontent.com/56211747/74249478-2e597f00-4d24-11ea-8818-d266872dcacf.png)

https://wskdsgcf.gitbook.io/mastering-go-zh-cn/2-go-nei-bu-ji-zhi/02.3/02.3.1

**Comment by hantmac** [comment]
感谢反馈，稍后修复一下。

**Comment by hantmac** [comment]
fix,如果还是加载不出图片，那就是GitHub最近抽风导致图片显示不出来
