### ISSUE TITLE
5.7章节：队列是一种特殊的链表，它总是在链表头添加新的元素，在链表尾删除元素。

### ISSUE THREAD

**Issue by GaiheiluKamei** [hantmac/Mastering_Go_ZH_CN#150]
队列不是队首删除，队尾插入吗？这里是不是弄错了？
看了下里面的代码实现是队尾插入，队首删除的。

**Comment by hantmac** [comment]
> 队列不是队首删除，队尾插入吗？这里是不是弄错了？
> 看了下里面的代码实现是队尾插入，队首删除的。

确实是头删尾增，感谢指正。方便的话提个PR修复下？

**Comment by GaiheiluKamei** [comment]
> > 队列不是队首删除，队尾插入吗？这里是不是弄错了？
> > 看了下里面的代码实现是队尾插入，队首删除的。
> 
> 确实是头删尾增，感谢指正。方便的话提个PR修复下？

额。。翻译的没错，原书写的也是队首增加，所以我来讨教一下，是不是原作者就弄错了？😈

> A queue is a special kind of linked list where each new element is inserted to the head and removed from the tail of the linked list.

**Comment by hantmac** [comment]
队列就是先进先出呀，感觉作者笔误写错了 🐶

**Comment by GaiheiluKamei** [comment]
> 队列就是先进先出呀，感觉作者笔误写错了 🐶

好，那我给你提个pr

**Comment by GaiheiluKamei** [comment]
我没权限。。你自己改吧

**Comment by hantmac** [comment]
> 我没权限。。你自己改吧

先fork仓库呀

**Comment by GaiheiluKamei** [comment]
> > 我没权限。。你自己改吧
> 
> 先fork仓库呀

没搞懂怎么弄，一直都是在公司直接ga, gc -m, gp的U+1F602

**Comment by hantmac** [comment]
可以顺便学下 git 😄
