### ISSUE TITLE
求大佬生成下MOBI

### ISSUE THREAD

**Issue by wangmengyu** [hantmac/Mastering_Go_ZH_CN#151]
方便我下载到我的Kindle

**Comment by hantmac** [comment]
已生成 mobi 文件，可以到 release 中下载 （不保证 mobi 的质量哇）

**Comment by wangmengyu** [comment]
> 已生成 mobi 文件，可以到 release 中下载 （不保证 mobi 的质量哇）

天哪格式看上去不太好啊, 都窝在一个竖条里显示了.

**Comment by wangmengyu** [comment]
> 已生成 mobi 文件，可以到 release 中下载 （不保证 mobi 的质量哇）

我找到办法啦 要再MAC上安装calibre, 
ln -s /Volumes/calibre-4.14.0/calibre.app/Contents/MacOS/ebook-convert /usr/local/bin

然后1. 安装nodejs: https://nodejs.org/en/ 
2. 安装gitbook-cli：npm install gitbook-cli -g 
3. git clone 电子书仓库: https://github.com/hantmac/Mastering_Go_ZH_CN/issues
4. sudo npm install svgexport -g --ignore-scripts
4. cd Mastering_Go_ZH_CN
5. gitbook fetch 3.2.3
5. gitbook mobi

**Comment by hantmac** [comment]
@wangmengyu 🐂🍺啊，可以把 mobi 版本贡献出来吗

**Comment by wangmengyu** [comment]
> @wangmengyu 🐂🍺啊，可以把 mobi 版本贡献出来吗

我发到你这个邮箱你可以收到吗 hantmac@outlook.com

**Comment by hantmac** [comment]
> > @wangmengyu 🐂🍺啊，可以把 mobi 版本贡献出来吗
> 
> 我发到你这个邮箱你可以收到吗 [hantmac@outlook.com](mailto:hantmac@outlook.com)

可以呀，发我吧。感谢！ ❤️

**Comment by wangmengyu** [comment]
> > > @wangmengyu 🐂🍺啊，可以把 mobi 版本贡献出来吗
> > 
> > 
> > 我发到你这个邮箱你可以收到吗 [hantmac@outlook.com](mailto:hantmac@outlook.com)
> 
> 可以呀，发我吧。感谢！ ❤️

你看看邮箱里有没有发送时间是：2020年4月30日(星期四) 晚上9:05的邮件， 附件中文件叫book.mobi

**Comment by hantmac** [comment]
收到了，感谢！
