### ISSUE TITLE
PDF文档的目录无法正常跳转

### ISSUE THREAD

**Issue by grzeng-go** [hantmac/Mastering_Go_ZH_CN#155]
PDF文档的目录无法正常跳转

**Comment by hantmac** [comment]
制作这个 PDF 的工具不太好，我再找别的工具试试

**Comment by wx-young** [comment]
借一步说话，  @hantmac   公众号群是不是进不去了

**Comment by hantmac** [comment]
> 借一步说话， @hantmac 公众号群是不是进不去了

卧槽确实是，加我 wx 拉你
